export const wedding = {
  bride: "Yuleisi",
  groom: "Elder",
  monogram: "Y & E",
  hashtag: "#BodaYuleisiYElder",
  title: "NUESTRA BODA",
  date: new Date(2026, 9, 24, 16, 0, 0),
  displayDate: "Sábado, 24 de Octubre de 2026",
  displayTime: "4:00 PM",
  city: "Lurigancho-Chosica, Lima",
  quote: "Hay momentos en la vida que son especiales por sí solos, pero compartirlos con las personas que quieres, los convierte en momentos inolvidables.",
  verse: {
    text: "Todo lo hizo hermoso en su tiempo",
    ref: "Eclesiastés 3:11",
  },
  song: {
    title: "Thinking Out Loud",
    artist: "Ed Sheeran",
    src: "./assets/song.m4a",
  },
  contact: {
    bride: {
      name: "Yuleisi",
      phone: "51987147762",
      displayPhone: "+51 987 147 762",
    },
    groom: {
      name: "Elder",
      phone: "51914854112",
      displayPhone: "+51 914 854 112",
    },
  },
  parents: {
    bride: {
      father: "José Diaz Ortiz",
      mother: "María Vergaray Villanueva",
    },
    groom: {
      father: "Anselmo Samame Paredes",
      mother: "Rosa Morales Ramirez",
      motherDeceased: true,
    },
  },
  events: [
    {
      type: "Ceremonia Religiosa",
      time: "4:30 PM",
      place: "El Gran Jardín Casa de Eventos",
      address: "Las Golondrinas 259, Lurigancho-Chosica, Lima 15457",
      google: "https://maps.app.goo.gl/8SQkrRxyt5BcNZ8m7",
      apple: "https://maps.apple.com/?q=El+Gran+Jardin+Casa+de+Eventos&ll=-12.0157098,-76.9447434",
      img: "rings.png",
      icon: "church",
    },
    {
      type: "Recepción",
      time: "6:30 PM",
      place: "El Gran Jardín Casa de Eventos",
      address: "Las Golondrinas 259, Lurigancho-Chosica, Lima 15457",
      google: "https://maps.app.goo.gl/8SQkrRxyt5BcNZ8m7",
      apple: "https://maps.apple.com/?q=El+Gran+Jardin+Casa+de+Eventos&ll=-12.0157098,-76.9447434",
      img: "venue.png",
      icon: "gazebo",
    },
  ],
  dress: {
    title: "Dresscode",
    type: "FORMAL",
    women: "Vestido largo",
    men: "Traje formal",
    note: "Agradecemos reservar los tonos Blanco, Perla, Marfil y Beige exclusivamente para la novia.",
    adultsTitle: "Solo Adultos",
    adults: "",
  },
  itinerary: [
    {
      time: "4:00 – 4:30 p. m.",
      title: "Recepción de invitados",
      desc: "Llegada y bienvenida de nuestros invitados",
      type: "reception",
    },
    {
      time: "4:30 p. m.",
      title: "Ceremonia religiosa",
      desc: "Bendición nupcial y unión ante el altar",
      type: "church",
    },
    {
      time: "6:00 p. m.",
      title: "Ceremonia protocolar",
      desc: "Brindis de honor, fotos y palabras especiales",
      type: "cocktail",
    },
    {
      time: "7:00 p. m.",
      title: "Cena",
      desc: "Banquete para compartir juntos",
      type: "dinner",
    },
    {
      time: "8:00 p. m.",
      title: "Apertura de baile",
      desc: "Música, baile y celebración",
      type: "dance",
    },
  ],
  gifts: {
    title: "Sugerencia de Regalo",
    intro: "Compartir este día con ustedes ya es muy especial para nosotros. Si desean tener un detalle, lo recibiremos con mucho cariño y gratitud.",
    homeTitle: "Obsequio en Dirección",
    homeNote: "Si desean enviarnos un obsequio, compartimos nuestra dirección:",
    homes: [
      {
        name: "Dirección de Recepción de Regalos",
        address: "Psj. Las Rosas Mz C Lt 12, Asoc. Las Begonias – Carabayllo",
      },
    ],
    accountTitle: "Transferencia / Cuentas",
    accountNote: "También dejamos disponibles estas opciones para quienes prefieran hacerlo de manera digital:",
    accounts: [
      {
        bank: "BCP",
        holder: "Yuleisi Paola Diaz Vergaray",
        account: "19197570498056",
        cci: "00219119757049805656",
      },
      {
        bank: "Yape",
        holder: "Yuleisi Paola Diaz Vergaray",
        account: "987 147 762",
        cci: "",
      },
    ],
    closing: "¡Gracias por ser parte de esta historia tan especial!",
  },
  closing: "Con mucha ilusión queremos vivir este momento rodeados de personas que han formado parte de nuestra historia. Será un honor contar con tu presencia.",
};
